live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
opacity = 0.9
decorations_theme_variant = "Dark"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 11.0

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "On" }
blink_interval = 500
blink_timeout = 3
unfocused_hollow = true
thickness = 0.15

[colors]
cursor = { text = "#282828", cursor = "#ebdbb2" }
vi_mode_cursor = { text = "#282828", cursor = "#ebdbb2" }
footer_bar = { foreground = "#282828", background = "#ebdbb2" }
line_indicator = { foreground = "None", background = "None" }
selection = { text = "CellBackground", background = "CellForeground" }

[colors.primary]
foreground = "#ebdbb2"
background = "#282828"
dim_foreground = "#a89984"

[colors.search]
matches = { foreground = "#282828", background = "#fe8019" }
focused_match = { foreground = "#282828", background = "#d65d0e" }

[colors.hints]
start = { foreground = "#282828", background = "#d65d0e" }
end = { foreground = "#282828", background = "#fe8019" }

[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

[colors.dim]
black = "#1d2021"
red = "#928374"
green = "#7c6f64"
yellow = "#d5c4a1"
blue = "#83a598"
magenta = "#bdae93"
cyan = "#8ec07c"
white = "#a89984"

